# Generated by Django 3.2.3 on 2021-06-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_image_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='base_64',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
