# Generated by Django 3.2.3 on 2021-06-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210621_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='base_64',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
