# Generated by Django 3.2.3 on 2021-06-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_image_base_64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='base_64',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
