# Generated by Django 3.2.4 on 2021-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210628_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
