# Generated by Django 3.2.4 on 2021-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderproduct_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
