# Generated by Django 3.2.4 on 2021-06-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_shopcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
